name: 'Labeler'
description: 'Add labels to new pull requests'
author: 'GitHub'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  labels:
    description: 'Comma separated list of labels to apply to the pull request'

runs:
  using: 'node12'
  main: 'dist/index.js'
